name: image_auth_push
on: [push, pull_request]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Debug
        run: echo "start build image debugicu/$GITHUB_REF_NAME:${{ github.event.inputs.tags }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 构建并推送到 Dockerhub 镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Dockerfile 位置
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: debugicu/${{ github.ref_name }}:latest